package com.sqlcompiler.domain.lexer;
public enum TokenType {
    SELECT, FROM, WHERE,
    INSERT, UPDATE, DELETE, CREATE,
    INTO, VALUES, SET,
    LIMIT, OFFSET,
    ORDER, GROUP, BY, HAVING,
    JOIN, INNER, LEFT, RIGHT, ON,
    AND, OR,
    ASC, DESC,
    ILIKE, RETURNING, AUTO_INCREMENT, ENGINE,
    IDENTIFIER, NUMBER, STRING,
    EQUAL, GREATER, LESS, GREATER_EQUAL, LESS_EQUAL, NOT_EQUAL,
    ASTERISK, COMMA, SEMICOLON,
    END_OF_FILE, INVALID
}
