package com.sqlcompiler.domain.lexer;
public enum TokenType {
    SELECT, FROM, WHERE,
    INSERT, UPDATE, DELETE, CREATE, TABLE,
    INTO, VALUES, SET,
    LIMIT, OFFSET, TOP,
    ORDER, GROUP, BY, HAVING,
    JOIN, INNER, LEFT, RIGHT, FULL, OUTER, ON,
    AND, OR, NOT, AS, IN, BETWEEN, LIKE,
    CASE, WHEN, THEN, ELSE, END,
    ASC, DESC,
    ILIKE, RETURNING, AUTO_INCREMENT, ENGINE,
    IDENTIFIER, NUMBER, STRING,
    EQUAL, GREATER, LESS, GREATER_EQUAL, LESS_EQUAL, NOT_EQUAL,
    ASTERISK, COMMA, SEMICOLON,
    LPAREN, RPAREN, DOT,
    END_OF_FILE, INVALID
}